# Generated by Django 3.2.9 on 2022-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(default=0, max_length=255, verbose_name='Максимальный объем встраиваемой памяти'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accum_volume',
            field=models.CharField(max_length=255, verbose_name='Объем батареи'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='frontal_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Главная камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True),
        ),
    ]
